services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file: C:\Users\Khach\OneDrive\Desktop\AI-Agents\.env
    depends_on:
      - db
    environment: 
      - DATABASE_URL=postgresql://user:password@db/reports_db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reports_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

